package PatternHeuristics;

import java.util.ArrayList;

import Go.SlickGo.Evaluator;
import Go.SlickGo.Pattern;
import Go.SlickGo.PatternSearcher;
import Go.SlickGo.Tuple;
import Go.SlickGo.UDLR;

public class PyramidFourv2 {
	Evaluator e;
	PatternSearcher ps;

	public PyramidFourv2 (Evaluator e){
		this.e=e;
	}



	public int evaluate(ArrayList<Tuple> sstring) {
		int retval = 0;
		ps = new PatternSearcher(e.cB,e.kscolour);
		
		ArrayList<Pattern> pattern = Pattern.sToPv2("xrxrxrdxdlxdlxluxlux", e.kscolour);
		ArrayList<ArrayList<Tuple>> pMatches =ps.allStringMatchv2(sstring, pattern);
		
		if(!pMatches.isEmpty()) {
			int counter=0;
			for(ArrayList<Tuple> tlist: pMatches) {
				if(!tlist.isEmpty()) {
					boolean diagSide= ps.dirSideToBool(counter);
					UDLR side = ps.dirNumToDir(counter);
					counter++;
					
					UDLR r = side.diag(diagSide);
					UDLR l = side.diag(!diagSide);
					Tuple S0 = tlist.get(0).side(side);
					Tuple S1 = S0.side(r);
					Tuple S2 = S1.side(r);
					Tuple D0 = S1.side(side);
					
					
					Tuple A1 = tlist.get(0).side(l);
					Tuple A2 = A1.side2(side,side);
					Tuple B1 = A2.side2(side,r);
					Tuple B2 = B1.side2(r,r);
					Tuple C1 = B2.side2(r,side.opp());
					Tuple C2 = C1.side2(side.opp(),side.opp());
					
					

//					if(e.isEnemies(A1,A2))continue;
//					if(e.isEnemies(B1,B2))continue;
//					if(e.isEnemies(C1,C2))continue;
					



					if(e.isThere(S0)||e.isThere(S2)||e.isThere(D0)) continue;
					String s = States.arrayToString(e,A1,A2,B1,B2,C1,C2,S0,S1,S2,D0);
					
					if (e.isThere(A1)) {
						if("ANNNNNNANN".equals(s)){retval+=1350;continue;}
						if("AENNNNNANN".equals(s)){retval+=1400;continue;}
						if("AEENNNNANN".equals(s)){retval+=1150;continue;}
						if("AEEENNNANN".equals(s)){retval+=900;continue;}
						if("AEEENENANN".equals(s)){retval+=500;continue;}
						if("AEEEEENANN".equals(s)){retval+=50;continue;}
						if("AEEEENNANN".equals(s)){retval+=500;continue;}
						if("AEENNENANN".equals(s)){retval+=950;continue;}
						if("AEENEENANN".equals(s)){retval+=500;continue;}
						if("AEENENNANN".equals(s)){retval+=950;continue;}
						if("AENENNNANN".equals(s)){retval+=1150;continue;}
						if("AENENENANN".equals(s)){retval+=950;continue;}
						if("AENEEENANN".equals(s)){retval+=500;continue;}
						if("AENEENNANN".equals(s)){retval+=950;continue;}
						if("AENNNENANN".equals(s)){retval+=1200;continue;}
						if("AENNEENANN".equals(s)){retval+=950;continue;}
						if("AENNENNANN".equals(s)){retval+=1200;continue;}
						if("ANENNNNANN".equals(s)){retval+=1100;continue;}
						if("ANEENNNANN".equals(s)){retval+=850;continue;}
						if("ANEENENANN".equals(s)){retval+=450;continue;}
						if("ANEEENNANN".equals(s)){retval+=450;continue;}
						if("ANENNENANN".equals(s)){retval+=900;continue;}
						if("ANENEENANN".equals(s)){retval+=450;continue;}
						if("ANENENNANN".equals(s)){retval+=900;continue;}
						if("ANNENNNANN".equals(s)){retval+=1100;continue;}
						if("ANNENENANN".equals(s)){retval+=900;continue;}
						if("ANNEEENANN".equals(s)){retval+=450;continue;}
						if("ANNEENNANN".equals(s)){retval+=900;continue;}
						if("ANNNNENANN".equals(s)){retval+=1150;continue;}
						if("ANNNEENANN".equals(s)){retval+=900;continue;}
						if("ANNNENNANN".equals(s)){retval+=1150;continue;}
						if("AANNNNNANN".equals(s)){retval+=1350;continue;}
						if("AAENNNNANN".equals(s)){retval+=1100;continue;}
						if("AAEENNNANN".equals(s)){retval+=850;continue;}
						if("AAEENENANN".equals(s)){retval+=450;continue;}
						if("AAEEENNANN".equals(s)){retval+=450;continue;}
						if("AAENNENANN".equals(s)){retval+=900;continue;}
						if("AAENEENANN".equals(s)){retval+=450;continue;}
						if("AAENENNANN".equals(s)){retval+=900;continue;}
						if("AANENNNANN".equals(s)){retval+=1100;continue;}
						if("AANENENANN".equals(s)){retval+=900;continue;}
						if("AANEEENANN".equals(s)){retval+=450;continue;}
						if("AANEENNANN".equals(s)){retval+=900;continue;}
						if("AANNNENANN".equals(s)){retval+=1150;continue;}
						if("AANNEENANN".equals(s)){retval+=900;continue;}
						if("AANNENNANN".equals(s)){retval+=1150;continue;}
						if("AAANNNNANN".equals(s)){retval+=450;continue;}
						if("AAAENNNANN".equals(s)){retval+=900;continue;}
						if("AAAENENANN".equals(s)){retval+=700;continue;}
						if("AAAEEENANN".equals(s)){retval+=450;continue;}
						if("AAAEENNANN".equals(s)){retval+=700;continue;}
						if("AAANNENANN".equals(s)){retval+=250;continue;}
						if("AAANENNANN".equals(s)){retval+=250;continue;}
						if("AAAANNNANN".equals(s)){retval+=450;continue;}
						if("AAAANENANN".equals(s)){retval+=250;continue;}
						if("AAAAENNANN".equals(s)){retval+=250;continue;}
						if("AAAANANANN".equals(s)){retval+=400;continue;}
						if("AAAAEANANN".equals(s)){retval+=450;continue;}
						if("AAAAAANANN".equals(s)){retval+=-400;continue;}
						if("AAAAANNANN".equals(s)){retval+=-400;continue;}
						if("AAAAAENANN".equals(s)){retval+=-400;continue;}
						if("AAANNANANN".equals(s)){retval+=400;continue;}
						if("AAAENANANN".equals(s)){retval+=850;continue;}
						if("AAAEEANANN".equals(s)){retval+=900;continue;}
						if("AAANEANANN".equals(s)){retval+=450;continue;}
						if("AAANAANANN".equals(s)){retval+=400;continue;}
						if("AAAEAANANN".equals(s)){retval+=850;continue;}
						if("AAANANNANN".equals(s)){retval+=400;continue;}
						if("AAAEANNANN".equals(s)){retval+=850;continue;}
						if("AAAEAENANN".equals(s)){retval+=900;continue;}
						if("AAANAENANN".equals(s)){retval+=450;continue;}
						if("AANANNNANN".equals(s)){retval+=1300;continue;}
						if("AAEANNNANN".equals(s)){retval+=1350;continue;}
						if("AAEANENANN".equals(s)){retval+=1150;continue;}
						if("AAEAEENANN".equals(s)){retval+=900;continue;}
						if("AAEAENNANN".equals(s)){retval+=1150;continue;}
						if("AANANENANN".equals(s)){retval+=1100;continue;}
						if("AANAEENANN".equals(s)){retval+=850;continue;}
						if("AANAENNANN".equals(s)){retval+=1100;continue;}
						if("AANANANANN".equals(s)){retval+=1250;continue;}
						if("AAEANANANN".equals(s)){retval+=1300;continue;}
						if("AAEAEANANN".equals(s)){retval+=1350;continue;}
						if("AANAEANANN".equals(s)){retval+=1300;continue;}
						if("AANAAANANN".equals(s)){retval+=400;continue;}
						if("AAEAAANANN".equals(s)){retval+=850;continue;}
						if("AANAANNANN".equals(s)){retval+=400;continue;}
						if("AAEAANNANN".equals(s)){retval+=850;continue;}
						if("AAEAAENANN".equals(s)){retval+=850;continue;}
						if("AANAAENANN".equals(s)){retval+=400;continue;}
						if("AANNNANANN".equals(s)){retval+=1300;continue;}
						if("AAENNANANN".equals(s)){retval+=1050;continue;}
						if("AAEENANANN".equals(s)){retval+=800;continue;}
						if("AAEEEANANN".equals(s)){retval+=850;continue;}
						if("AAENEANANN".equals(s)){retval+=1100;continue;}
						if("AANENANANN".equals(s)){retval+=1050;continue;}
						if("AANEEANANN".equals(s)){retval+=1100;continue;}
						if("AANNEANANN".equals(s)){retval+=1350;continue;}
						if("AANNAANANN".equals(s)){retval+=1300;continue;}
						if("AAENAANANN".equals(s)){retval+=1050;continue;}
						if("AAEEAANANN".equals(s)){retval+=800;continue;}
						if("AANEAANANN".equals(s)){retval+=1050;continue;}
						if("AANNANNANN".equals(s)){retval+=1300;continue;}
						if("AAENANNANN".equals(s)){retval+=1050;continue;}
						if("AAEEANNANN".equals(s)){retval+=800;continue;}
						if("AAEEAENANN".equals(s)){retval+=850;continue;}
						if("AAENAENANN".equals(s)){retval+=1100;continue;}
						if("AANEANNANN".equals(s)){retval+=1050;continue;}
						if("AANEAENANN".equals(s)){retval+=1100;continue;}
						if("AANNAENANN".equals(s)){retval+=1350;continue;}
						if("ANANNNNANN".equals(s)){retval+=1300;continue;}
						if("AEANNNNANN".equals(s)){retval+=1350;continue;}
						if("AEAENNNANN".equals(s)){retval+=1400;continue;}
						if("AEAENENANN".equals(s)){retval+=1200;continue;}
						if("AEAEEENANN".equals(s)){retval+=950;continue;}
						if("AEAEENNANN".equals(s)){retval+=1200;continue;}
						if("AEANNENANN".equals(s)){retval+=1150;continue;}
						if("AEANEENANN".equals(s)){retval+=900;continue;}
						if("AEANENNANN".equals(s)){retval+=1150;continue;}
						if("ANAENNNANN".equals(s)){retval+=1350;continue;}
						if("ANAENENANN".equals(s)){retval+=1150;continue;}
						if("ANAEEENANN".equals(s)){retval+=900;continue;}
						if("ANAEENNANN".equals(s)){retval+=1150;continue;}
						if("ANANNENANN".equals(s)){retval+=1100;continue;}
						if("ANANEENANN".equals(s)){retval+=850;continue;}
						if("ANANENNANN".equals(s)){retval+=1100;continue;}
						if("ANAANNNANN".equals(s)){retval+=1250;continue;}
						if("AEAANNNANN".equals(s)){retval+=1300;continue;}
						if("AEAANENANN".equals(s)){retval+=1100;continue;}
						if("AEAAEENANN".equals(s)){retval+=850;continue;}
						if("AEAAENNANN".equals(s)){retval+=1100;continue;}
						if("ANAANENANN".equals(s)){retval+=1050;continue;}
						if("ANAAEENANN".equals(s)){retval+=800;continue;}
						if("ANAAENNANN".equals(s)){retval+=1050;continue;}
						if("ANAANANANN".equals(s)){retval+=1200;continue;}
						if("AEAANANANN".equals(s)){retval+=1250;continue;}
						if("AEAAEANANN".equals(s)){retval+=1300;continue;}
						if("ANAAEANANN".equals(s)){retval+=1250;continue;}
						if("ANAAAANANN".equals(s)){retval+=400;continue;}
						if("AEAAAANANN".equals(s)){retval+=450;continue;}
						if("ANAAANNANN".equals(s)){retval+=400;continue;}
						if("AEAAANNANN".equals(s)){retval+=450;continue;}
						if("AEAAAENANN".equals(s)){retval+=450;continue;}
						if("ANAAAENANN".equals(s)){retval+=400;continue;}
						if("ANANNANANN".equals(s)){retval+=1250;continue;}
						if("AEANNANANN".equals(s)){retval+=1300;continue;}
						if("AEAENANANN".equals(s)){retval+=1350;continue;}
						if("AEAEEANANN".equals(s)){retval+=1400;continue;}
						if("AEANEANANN".equals(s)){retval+=1350;continue;}
						if("ANAENANANN".equals(s)){retval+=1300;continue;}
						if("ANAEEANANN".equals(s)){retval+=1350;continue;}
						if("ANANEANANN".equals(s)){retval+=1300;continue;}
						if("ANANAANANN".equals(s)){retval+=1250;continue;}
						if("AEANAANANN".equals(s)){retval+=1300;continue;}
						if("AEAEAANANN".equals(s)){retval+=1350;continue;}
						if("ANAEAANANN".equals(s)){retval+=1300;continue;}
						if("ANANANNANN".equals(s)){retval+=1250;continue;}
						if("AEANANNANN".equals(s)){retval+=1300;continue;}
						if("AEAEANNANN".equals(s)){retval+=1350;continue;}
						if("AEAEAENANN".equals(s)){retval+=1400;continue;}
						if("AEANAENANN".equals(s)){retval+=1350;continue;}
						if("ANAEANNANN".equals(s)){retval+=1300;continue;}
						if("ANAEAENANN".equals(s)){retval+=1350;continue;}
						if("ANANAENANN".equals(s)){retval+=1300;continue;}
						if("ANNANNNANN".equals(s)){retval+=1300;continue;}
						if("AENANNNANN".equals(s)){retval+=1350;continue;}
						if("AEEANNNANN".equals(s)){retval+=1400;continue;}
						if("AEEANENANN".equals(s)){retval+=1200;continue;}
						if("AEEAEENANN".equals(s)){retval+=950;continue;}
						if("AEEAENNANN".equals(s)){retval+=1200;continue;}
						if("AENANENANN".equals(s)){retval+=1150;continue;}
						if("AENAEENANN".equals(s)){retval+=900;continue;}
						if("AENAENNANN".equals(s)){retval+=1150;continue;}
						if("ANEANNNANN".equals(s)){retval+=1350;continue;}
						if("ANEANENANN".equals(s)){retval+=1150;continue;}
						if("ANEAEENANN".equals(s)){retval+=900;continue;}
						if("ANEAENNANN".equals(s)){retval+=1150;continue;}
						if("ANNANENANN".equals(s)){retval+=1100;continue;}
						if("ANNAEENANN".equals(s)){retval+=850;continue;}
						if("ANNAENNANN".equals(s)){retval+=1100;continue;}
						if("ANNANANANN".equals(s)){retval+=1250;continue;}
						if("AENANANANN".equals(s)){retval+=1300;continue;}
						if("AEEANANANN".equals(s)){retval+=1350;continue;}
						if("AEEAEANANN".equals(s)){retval+=1400;continue;}
						if("AENAEANANN".equals(s)){retval+=1350;continue;}
						if("ANEANANANN".equals(s)){retval+=1300;continue;}
						if("ANEAEANANN".equals(s)){retval+=1350;continue;}
						if("ANNAEANANN".equals(s)){retval+=1300;continue;}
						if("ANNAAANANN".equals(s)){retval+=400;continue;}
						if("AENAAANANN".equals(s)){retval+=450;continue;}
						if("AEEAAANANN".equals(s)){retval+=900;continue;}
						if("ANEAAANANN".equals(s)){retval+=850;continue;}
						if("ANNAANNANN".equals(s)){retval+=400;continue;}
						if("AENAANNANN".equals(s)){retval+=450;continue;}
						if("AEEAANNANN".equals(s)){retval+=900;continue;}
						if("AEEAAENANN".equals(s)){retval+=900;continue;}
						if("AENAAENANN".equals(s)){retval+=450;continue;}
						if("ANEAANNANN".equals(s)){retval+=850;continue;}
						if("ANEAAENANN".equals(s)){retval+=850;continue;}
						if("ANNAAENANN".equals(s)){retval+=400;continue;}
						if("ANNNNANANN".equals(s)){retval+=1300;continue;}
						if("AENNNANANN".equals(s)){retval+=1350;continue;}
						if("AEENNANANN".equals(s)){retval+=1100;continue;}
						if("AEEENANANN".equals(s)){retval+=850;continue;}
						if("AEEEEANANN".equals(s)){retval+=900;continue;}
						if("AEENEANANN".equals(s)){retval+=1150;continue;}
						if("AENENANANN".equals(s)){retval+=1100;continue;}
						if("AENEEANANN".equals(s)){retval+=1150;continue;}
						if("AENNEANANN".equals(s)){retval+=1400;continue;}
						if("ANENNANANN".equals(s)){retval+=1050;continue;}
						if("ANEENANANN".equals(s)){retval+=800;continue;}
						if("ANEEEANANN".equals(s)){retval+=850;continue;}
						if("ANENEANANN".equals(s)){retval+=1100;continue;}
						if("ANNENANANN".equals(s)){retval+=1050;continue;}
						if("ANNEEANANN".equals(s)){retval+=1100;continue;}
						if("ANNNEANANN".equals(s)){retval+=1350;continue;}
						if("ANNNAANANN".equals(s)){retval+=1300;continue;}
						if("AENNAANANN".equals(s)){retval+=1350;continue;}
						if("AEENAANANN".equals(s)){retval+=1100;continue;}
						if("AEEEAANANN".equals(s)){retval+=850;continue;}
						if("AENEAANANN".equals(s)){retval+=1100;continue;}
						if("ANENAANANN".equals(s)){retval+=1050;continue;}
						if("ANEEAANANN".equals(s)){retval+=800;continue;}
						if("ANNEAANANN".equals(s)){retval+=1050;continue;}
						if("ANNNANNANN".equals(s)){retval+=1300;continue;}
						if("AENNANNANN".equals(s)){retval+=1350;continue;}
						if("AEENANNANN".equals(s)){retval+=1100;continue;}
						if("AEEEANNANN".equals(s)){retval+=850;continue;}
						if("AEEEAENANN".equals(s)){retval+=900;continue;}
						if("AEENAENANN".equals(s)){retval+=1150;continue;}
						if("AENEANNANN".equals(s)){retval+=1100;continue;}
						if("AENEAENANN".equals(s)){retval+=1150;continue;}
						if("AENNAENANN".equals(s)){retval+=1400;continue;}
						if("ANENANNANN".equals(s)){retval+=1050;continue;}
						if("ANEEANNANN".equals(s)){retval+=800;continue;}
						if("ANEEAENANN".equals(s)){retval+=850;continue;}
						if("ANENAENANN".equals(s)){retval+=1100;continue;}
						if("ANNEANNANN".equals(s)){retval+=1050;continue;}
						if("ANNEAENANN".equals(s)){retval+=1100;continue;}
						if("ANNNAENANN".equals(s)){retval+=1350;continue;}
					}else if(e.isEnemy(A1)){
						if("ENNNNNNANN".equals(s)){retval+=1200;continue;}
						if("EENNNNNANN".equals(s)){retval+=950;continue;}
						if("EEENNNNANN".equals(s)){retval+=500;continue;}
						if("EEEENNNANN".equals(s)){retval+=50;continue;}
						if("EEEENENANN".equals(s)){retval+=50;continue;}
						if("EEEEENNANN".equals(s)){retval+=50;continue;}
						if("EEENNENANN".equals(s)){retval+=100;continue;}
						if("EEENEENANN".equals(s)){retval+=50;continue;}
						if("EEENENNANN".equals(s)){retval+=100;continue;}
						if("EENENNNANN".equals(s)){retval+=500;continue;}
						if("EENENENANN".equals(s)){retval+=100;continue;}
						if("EENEEENANN".equals(s)){retval+=50;continue;}
						if("EENEENNANN".equals(s)){retval+=100;continue;}
						if("EENNNENANN".equals(s)){retval+=550;continue;}
						if("EENNEENANN".equals(s)){retval+=100;continue;}
						if("EENNENNANN".equals(s)){retval+=550;continue;}
						if("ENENNNNANN".equals(s)){retval+=950;continue;}
						if("ENEENNNANN".equals(s)){retval+=500;continue;}
						if("ENEENENANN".equals(s)){retval+=100;continue;}
						if("ENEEEENANN".equals(s)){retval+=50;continue;}
						if("ENEEENNANN".equals(s)){retval+=100;continue;}
						if("ENENNENANN".equals(s)){retval+=550;continue;}
						if("ENENEENANN".equals(s)){retval+=100;continue;}
						if("ENENENNANN".equals(s)){retval+=550;continue;}
						if("ENNENNNANN".equals(s)){retval+=950;continue;}
						if("ENNENENANN".equals(s)){retval+=550;continue;}
						if("ENNEEENANN".equals(s)){retval+=100;continue;}
						if("ENNEENNANN".equals(s)){retval+=550;continue;}
						if("ENNNNENANN".equals(s)){retval+=1000;continue;}
						if("ENNNEENANN".equals(s)){retval+=550;continue;}
						if("ENNNENNANN".equals(s)){retval+=1000;continue;}
						if("EANNNNNANN".equals(s)){retval+=1400;continue;}
						if("EAENNNNANN".equals(s)){retval+=1150;continue;}
						if("EAEENNNANN".equals(s)){retval+=900;continue;}
						if("EAEENENANN".equals(s)){retval+=500;continue;}
						if("EAEEEENANN".equals(s)){retval+=50;continue;}
						if("EAEEENNANN".equals(s)){retval+=500;continue;}
						if("EAENNENANN".equals(s)){retval+=950;continue;}
						if("EAENEENANN".equals(s)){retval+=500;continue;}
						if("EAENENNANN".equals(s)){retval+=950;continue;}
						if("EANENNNANN".equals(s)){retval+=1150;continue;}
						if("EANENENANN".equals(s)){retval+=950;continue;}
						if("EANEEENANN".equals(s)){retval+=500;continue;}
						if("EANEENNANN".equals(s)){retval+=950;continue;}
						if("EANNNENANN".equals(s)){retval+=1200;continue;}
						if("EANNEENANN".equals(s)){retval+=950;continue;}
						if("EANNENNANN".equals(s)){retval+=1200;continue;}
						if("EAANNNNANN".equals(s)){retval+=450;continue;}
						if("EAAENNNANN".equals(s)){retval+=900;continue;}
						if("EAAENENANN".equals(s)){retval+=700;continue;}
						if("EAAEEENANN".equals(s)){retval+=450;continue;}
						if("EAAEENNANN".equals(s)){retval+=700;continue;}
						if("EAANNENANN".equals(s)){retval+=250;continue;}
						if("EAANENNANN".equals(s)){retval+=250;continue;}
						if("EAAANNNANN".equals(s)){retval+=450;continue;}
						if("EAAANENANN".equals(s)){retval+=250;continue;}
						if("EAAAENNANN".equals(s)){retval+=250;continue;}
						if("EAAANANANN".equals(s)){retval+=400;continue;}
						if("EAAAEANANN".equals(s)){retval+=450;continue;}
						if("EAAAAANANN".equals(s)){retval+=-400;continue;}
						if("EAAAANNANN".equals(s)){retval+=-400;continue;}
						if("EAAAAENANN".equals(s)){retval+=-400;continue;}
						if("EAANNANANN".equals(s)){retval+=400;continue;}
						if("EAAENANANN".equals(s)){retval+=850;continue;}
						if("EAAEEANANN".equals(s)){retval+=900;continue;}
						if("EAANEANANN".equals(s)){retval+=450;continue;}
						if("EAANAANANN".equals(s)){retval+=400;continue;}
						if("EAAEAANANN".equals(s)){retval+=850;continue;}
						if("EAANANNANN".equals(s)){retval+=400;continue;}
						if("EAAEANNANN".equals(s)){retval+=850;continue;}
						if("EAAEAENANN".equals(s)){retval+=900;continue;}
						if("EAANAENANN".equals(s)){retval+=450;continue;}
						if("EANANNNANN".equals(s)){retval+=1350;continue;}
						if("EAEANNNANN".equals(s)){retval+=1400;continue;}
						if("EAEANENANN".equals(s)){retval+=1200;continue;}
						if("EAEAEENANN".equals(s)){retval+=950;continue;}
						if("EAEAENNANN".equals(s)){retval+=1200;continue;}
						if("EANANENANN".equals(s)){retval+=1150;continue;}
						if("EANAEENANN".equals(s)){retval+=900;continue;}
						if("EANAENNANN".equals(s)){retval+=1150;continue;}
						if("EANANANANN".equals(s)){retval+=1300;continue;}
						if("EAEANANANN".equals(s)){retval+=1350;continue;}
						if("EAEAEANANN".equals(s)){retval+=1400;continue;}
						if("EANAEANANN".equals(s)){retval+=1350;continue;}
						if("EANAAANANN".equals(s)){retval+=450;continue;}
						if("EAEAAANANN".equals(s)){retval+=900;continue;}
						if("EANAANNANN".equals(s)){retval+=450;continue;}
						if("EAEAANNANN".equals(s)){retval+=900;continue;}
						if("EAEAAENANN".equals(s)){retval+=900;continue;}
						if("EANAAENANN".equals(s)){retval+=450;continue;}
						if("EANNNANANN".equals(s)){retval+=1350;continue;}
						if("EAENNANANN".equals(s)){retval+=1100;continue;}
						if("EAEENANANN".equals(s)){retval+=850;continue;}
						if("EAEEEANANN".equals(s)){retval+=900;continue;}
						if("EAENEANANN".equals(s)){retval+=1150;continue;}
						if("EANENANANN".equals(s)){retval+=1100;continue;}
						if("EANEEANANN".equals(s)){retval+=1150;continue;}
						if("EANNEANANN".equals(s)){retval+=1400;continue;}
						if("EANNAANANN".equals(s)){retval+=1350;continue;}
						if("EAENAANANN".equals(s)){retval+=1100;continue;}
						if("EAEEAANANN".equals(s)){retval+=850;continue;}
						if("EANEAANANN".equals(s)){retval+=1100;continue;}
						if("EANNANNANN".equals(s)){retval+=1350;continue;}
						if("EAENANNANN".equals(s)){retval+=1100;continue;}
						if("EAEEANNANN".equals(s)){retval+=850;continue;}
						if("EAEEAENANN".equals(s)){retval+=900;continue;}
						if("EAENAENANN".equals(s)){retval+=1150;continue;}
						if("EANEANNANN".equals(s)){retval+=1100;continue;}
						if("EANEAENANN".equals(s)){retval+=1150;continue;}
						if("EANNAENANN".equals(s)){retval+=1400;continue;}
						if("ENANNNNANN".equals(s)){retval+=1150;continue;}
						if("EEANNNNANN".equals(s)){retval+=900;continue;}
						if("EEAENNNANN".equals(s)){retval+=950;continue;}
						if("EEAENENANN".equals(s)){retval+=550;continue;}
						if("EEAEEENANN".equals(s)){retval+=100;continue;}
						if("EEAEENNANN".equals(s)){retval+=550;continue;}
						if("EEANNENANN".equals(s)){retval+=500;continue;}
						if("EEANEENANN".equals(s)){retval+=50;continue;}
						if("EEANENNANN".equals(s)){retval+=500;continue;}
						if("ENAENNNANN".equals(s)){retval+=1200;continue;}
						if("ENAENENANN".equals(s)){retval+=1000;continue;}
						if("ENAEEENANN".equals(s)){retval+=550;continue;}
						if("ENAEENNANN".equals(s)){retval+=1000;continue;}
						if("ENANNENANN".equals(s)){retval+=950;continue;}
						if("ENANEENANN".equals(s)){retval+=500;continue;}
						if("ENANENNANN".equals(s)){retval+=950;continue;}
						if("ENAANNNANN".equals(s)){retval+=1100;continue;}
						if("EEAANNNANN".equals(s)){retval+=850;continue;}
						if("EEAANENANN".equals(s)){retval+=450;continue;}
						if("EEAAENNANN".equals(s)){retval+=450;continue;}
						if("ENAANENANN".equals(s)){retval+=900;continue;}
						if("ENAAEENANN".equals(s)){retval+=450;continue;}
						if("ENAAENNANN".equals(s)){retval+=900;continue;}
						if("ENAANANANN".equals(s)){retval+=1050;continue;}
						if("EEAANANANN".equals(s)){retval+=800;continue;}
						if("EEAAEANANN".equals(s)){retval+=850;continue;}
						if("ENAAEANANN".equals(s)){retval+=1100;continue;}
						if("ENAAAANANN".equals(s)){retval+=250;continue;}
						if("ENAAANNANN".equals(s)){retval+=250;continue;}
						if("ENAAAENANN".equals(s)){retval+=250;continue;}
						if("ENANNANANN".equals(s)){retval+=1100;continue;}
						if("EEANNANANN".equals(s)){retval+=850;continue;}
						if("EEAENANANN".equals(s)){retval+=900;continue;}
						if("EEAEEANANN".equals(s)){retval+=950;continue;}
						if("EEANEANANN".equals(s)){retval+=900;continue;}
						if("ENAENANANN".equals(s)){retval+=1150;continue;}
						if("ENAEEANANN".equals(s)){retval+=1200;continue;}
						if("ENANEANANN".equals(s)){retval+=1150;continue;}
						if("ENANAANANN".equals(s)){retval+=1100;continue;}
						if("EEANAANANN".equals(s)){retval+=850;continue;}
						if("EEAEAANANN".equals(s)){retval+=900;continue;}
						if("ENAEAANANN".equals(s)){retval+=1150;continue;}
						if("ENANANNANN".equals(s)){retval+=1100;continue;}
						if("EEANANNANN".equals(s)){retval+=850;continue;}
						if("EEAEANNANN".equals(s)){retval+=900;continue;}
						if("EEAEAENANN".equals(s)){retval+=950;continue;}
						if("EEANAENANN".equals(s)){retval+=900;continue;}
						if("ENAEANNANN".equals(s)){retval+=1150;continue;}
						if("ENAEAENANN".equals(s)){retval+=1200;continue;}
						if("ENANAENANN".equals(s)){retval+=1150;continue;}
						if("ENNANNNANN".equals(s)){retval+=1150;continue;}
						if("EENANNNANN".equals(s)){retval+=900;continue;}
						if("EEEANNNANN".equals(s)){retval+=950;continue;}
						if("EEEANENANN".equals(s)){retval+=550;continue;}
						if("EEEAEENANN".equals(s)){retval+=100;continue;}
						if("EEEAENNANN".equals(s)){retval+=550;continue;}
						if("EENANENANN".equals(s)){retval+=500;continue;}
						if("EENAEENANN".equals(s)){retval+=50;continue;}
						if("EENAENNANN".equals(s)){retval+=500;continue;}
						if("ENEANNNANN".equals(s)){retval+=1200;continue;}
						if("ENEANENANN".equals(s)){retval+=1000;continue;}
						if("ENEAEENANN".equals(s)){retval+=550;continue;}
						if("ENEAENNANN".equals(s)){retval+=1000;continue;}
						if("ENNANENANN".equals(s)){retval+=950;continue;}
						if("ENNAEENANN".equals(s)){retval+=500;continue;}
						if("ENNAENNANN".equals(s)){retval+=950;continue;}
						if("ENNANANANN".equals(s)){retval+=1100;continue;}
						if("EENANANANN".equals(s)){retval+=850;continue;}
						if("EEEANANANN".equals(s)){retval+=900;continue;}
						if("EEEAEANANN".equals(s)){retval+=950;continue;}
						if("EENAEANANN".equals(s)){retval+=900;continue;}
						if("ENEANANANN".equals(s)){retval+=1150;continue;}
						if("ENEAEANANN".equals(s)){retval+=1200;continue;}
						if("ENNAEANANN".equals(s)){retval+=1150;continue;}
						if("ENNAAANANN".equals(s)){retval+=250;continue;}
						if("EEEAAANANN".equals(s)){retval+=450;continue;}
						if("ENEAAANANN".equals(s)){retval+=700;continue;}
						if("ENNAANNANN".equals(s)){retval+=250;continue;}
						if("EEEAANNANN".equals(s)){retval+=450;continue;}
						if("EEEAAENANN".equals(s)){retval+=450;continue;}
						if("ENEAANNANN".equals(s)){retval+=700;continue;}
						if("ENEAAENANN".equals(s)){retval+=700;continue;}
						if("ENNAAENANN".equals(s)){retval+=250;continue;}
						if("ENNNNANANN".equals(s)){retval+=1150;continue;}
						if("EENNNANANN".equals(s)){retval+=900;continue;}
						if("EEENNANANN".equals(s)){retval+=450;continue;}
						if("EEEEEANANN".equals(s)){retval+=50;continue;}
						if("EEENEANANN".equals(s)){retval+=500;continue;}
						if("EENENANANN".equals(s)){retval+=450;continue;}
						if("EENEEANANN".equals(s)){retval+=500;continue;}
						if("EENNEANANN".equals(s)){retval+=950;continue;}
						if("ENENNANANN".equals(s)){retval+=900;continue;}
						if("ENEENANANN".equals(s)){retval+=450;continue;}
						if("ENEEEANANN".equals(s)){retval+=500;continue;}
						if("ENENEANANN".equals(s)){retval+=950;continue;}
						if("ENNENANANN".equals(s)){retval+=900;continue;}
						if("ENNEEANANN".equals(s)){retval+=950;continue;}
						if("ENNNEANANN".equals(s)){retval+=1200;continue;}
						if("ENNNAANANN".equals(s)){retval+=1150;continue;}
						if("EENNAANANN".equals(s)){retval+=900;continue;}
						if("EEENAANANN".equals(s)){retval+=450;continue;}
						if("EENEAANANN".equals(s)){retval+=450;continue;}
						if("ENENAANANN".equals(s)){retval+=900;continue;}
						if("ENEEAANANN".equals(s)){retval+=450;continue;}
						if("ENNEAANANN".equals(s)){retval+=900;continue;}
						if("ENNNANNANN".equals(s)){retval+=1150;continue;}
						if("EENNANNANN".equals(s)){retval+=900;continue;}
						if("EEENANNANN".equals(s)){retval+=450;continue;}
						if("EEEEAENANN".equals(s)){retval+=50;continue;}
						if("EEENAENANN".equals(s)){retval+=500;continue;}
						if("EENEANNANN".equals(s)){retval+=450;continue;}
						if("EENEAENANN".equals(s)){retval+=500;continue;}
						if("EENNAENANN".equals(s)){retval+=950;continue;}
						if("ENENANNANN".equals(s)){retval+=900;continue;}
						if("ENEEANNANN".equals(s)){retval+=450;continue;}
						if("ENEEAENANN".equals(s)){retval+=500;continue;}
						if("ENENAENANN".equals(s)){retval+=950;continue;}
						if("ENNEANNANN".equals(s)){retval+=900;continue;}
						if("ENNEAENANN".equals(s)){retval+=950;continue;}
						if("ENNNAENANN".equals(s)){retval+=1200;continue;}
					}else {
						if("NNNNNNNANN".equals(s)){retval+=1400;continue;}
						if("NENNNNNANN".equals(s)){retval+=1200;continue;}
						if("NEENNNNANN".equals(s)){retval+=950;continue;}
						if("NEEENNNANN".equals(s)){retval+=500;continue;}
						if("NEEENENANN".equals(s)){retval+=100;continue;}
						if("NEEEEENANN".equals(s)){retval+=50;continue;}
						if("NEEEENNANN".equals(s)){retval+=100;continue;}
						if("NEENNENANN".equals(s)){retval+=550;continue;}
						if("NEENEENANN".equals(s)){retval+=100;continue;}
						if("NEENENNANN".equals(s)){retval+=550;continue;}
						if("NENENNNANN".equals(s)){retval+=950;continue;}
						if("NENENENANN".equals(s)){retval+=550;continue;}
						if("NENEEENANN".equals(s)){retval+=100;continue;}
						if("NENEENNANN".equals(s)){retval+=550;continue;}
						if("NENNNENANN".equals(s)){retval+=1000;continue;}
						if("NENNEENANN".equals(s)){retval+=550;continue;}
						if("NENNENNANN".equals(s)){retval+=1000;continue;}
						if("NNENNNNANN".equals(s)){retval+=1150;continue;}
						if("NNEENNNANN".equals(s)){retval+=900;continue;}
						if("NNEENENANN".equals(s)){retval+=500;continue;}
						if("NNEEEENANN".equals(s)){retval+=50;continue;}
						if("NNEEENNANN".equals(s)){retval+=500;continue;}
						if("NNENNENANN".equals(s)){retval+=950;continue;}
						if("NNENEENANN".equals(s)){retval+=500;continue;}
						if("NNENENNANN".equals(s)){retval+=950;continue;}
						if("NNNENNNANN".equals(s)){retval+=1150;continue;}
						if("NNNENENANN".equals(s)){retval+=950;continue;}
						if("NNNEEENANN".equals(s)){retval+=500;continue;}
						if("NNNEENNANN".equals(s)){retval+=950;continue;}
						if("NNNNNENANN".equals(s)){retval+=1200;continue;}
						if("NNNNEENANN".equals(s)){retval+=950;continue;}
						if("NNNNENNANN".equals(s)){retval+=1200;continue;}
						if("NANNNNNANN".equals(s)){retval+=1350;continue;}
						if("NAENNNNANN".equals(s)){retval+=1100;continue;}
						if("NAEENNNANN".equals(s)){retval+=850;continue;}
						if("NAEENENANN".equals(s)){retval+=450;continue;}
						if("NAEEENNANN".equals(s)){retval+=450;continue;}
						if("NAENNENANN".equals(s)){retval+=900;continue;}
						if("NAENEENANN".equals(s)){retval+=450;continue;}
						if("NAENENNANN".equals(s)){retval+=900;continue;}
						if("NANENNNANN".equals(s)){retval+=1100;continue;}
						if("NANENENANN".equals(s)){retval+=900;continue;}
						if("NANEEENANN".equals(s)){retval+=450;continue;}
						if("NANEENNANN".equals(s)){retval+=900;continue;}
						if("NANNNENANN".equals(s)){retval+=1150;continue;}
						if("NANNEENANN".equals(s)){retval+=900;continue;}
						if("NANNENNANN".equals(s)){retval+=1150;continue;}
						if("NAANNNNANN".equals(s)){retval+=450;continue;}
						if("NAAENNNANN".equals(s)){retval+=900;continue;}
						if("NAAENENANN".equals(s)){retval+=700;continue;}
						if("NAAEEENANN".equals(s)){retval+=450;continue;}
						if("NAAEENNANN".equals(s)){retval+=700;continue;}
						if("NAANNENANN".equals(s)){retval+=250;continue;}
						if("NAANENNANN".equals(s)){retval+=250;continue;}
						if("NAAANNNANN".equals(s)){retval+=450;continue;}
						if("NAAANENANN".equals(s)){retval+=250;continue;}
						if("NAAAENNANN".equals(s)){retval+=250;continue;}
						if("NAAANANANN".equals(s)){retval+=400;continue;}
						if("NAAAEANANN".equals(s)){retval+=450;continue;}
						if("NAAAAANANN".equals(s)){retval+=-400;continue;}
						if("NAAAANNANN".equals(s)){retval+=-400;continue;}
						if("NAAAAENANN".equals(s)){retval+=-400;continue;}
						if("NAANNANANN".equals(s)){retval+=400;continue;}
						if("NAAENANANN".equals(s)){retval+=850;continue;}
						if("NAAEEANANN".equals(s)){retval+=900;continue;}
						if("NAANEANANN".equals(s)){retval+=450;continue;}
						if("NAANAANANN".equals(s)){retval+=400;continue;}
						if("NAAEAANANN".equals(s)){retval+=850;continue;}
						if("NAANANNANN".equals(s)){retval+=400;continue;}
						if("NAAEANNANN".equals(s)){retval+=850;continue;}
						if("NAAEAENANN".equals(s)){retval+=900;continue;}
						if("NAANAENANN".equals(s)){retval+=450;continue;}
						if("NANANNNANN".equals(s)){retval+=1300;continue;}
						if("NAEANNNANN".equals(s)){retval+=1350;continue;}
						if("NAEANENANN".equals(s)){retval+=1150;continue;}
						if("NAEAEENANN".equals(s)){retval+=900;continue;}
						if("NAEAENNANN".equals(s)){retval+=1150;continue;}
						if("NANANENANN".equals(s)){retval+=1100;continue;}
						if("NANAEENANN".equals(s)){retval+=850;continue;}
						if("NANAENNANN".equals(s)){retval+=1100;continue;}
						if("NANANANANN".equals(s)){retval+=1250;continue;}
						if("NAEANANANN".equals(s)){retval+=1300;continue;}
						if("NAEAEANANN".equals(s)){retval+=1350;continue;}
						if("NANAEANANN".equals(s)){retval+=1300;continue;}
						if("NANAAANANN".equals(s)){retval+=400;continue;}
						if("NAEAAANANN".equals(s)){retval+=850;continue;}
						if("NANAANNANN".equals(s)){retval+=400;continue;}
						if("NAEAANNANN".equals(s)){retval+=850;continue;}
						if("NAEAAENANN".equals(s)){retval+=850;continue;}
						if("NANAAENANN".equals(s)){retval+=400;continue;}
						if("NANNNANANN".equals(s)){retval+=1300;continue;}
						if("NAENNANANN".equals(s)){retval+=1050;continue;}
						if("NAEENANANN".equals(s)){retval+=800;continue;}
						if("NAEEEANANN".equals(s)){retval+=850;continue;}
						if("NAENEANANN".equals(s)){retval+=1100;continue;}
						if("NANENANANN".equals(s)){retval+=1050;continue;}
						if("NANEEANANN".equals(s)){retval+=1100;continue;}
						if("NANNEANANN".equals(s)){retval+=1350;continue;}
						if("NANNAANANN".equals(s)){retval+=1300;continue;}
						if("NAENAANANN".equals(s)){retval+=1050;continue;}
						if("NAEEAANANN".equals(s)){retval+=800;continue;}
						if("NANEAANANN".equals(s)){retval+=1050;continue;}
						if("NANNANNANN".equals(s)){retval+=1300;continue;}
						if("NAENANNANN".equals(s)){retval+=1050;continue;}
						if("NAEEANNANN".equals(s)){retval+=800;continue;}
						if("NAEEAENANN".equals(s)){retval+=850;continue;}
						if("NAENAENANN".equals(s)){retval+=1100;continue;}
						if("NANEANNANN".equals(s)){retval+=1050;continue;}
						if("NANEAENANN".equals(s)){retval+=1100;continue;}
						if("NANNAENANN".equals(s)){retval+=1350;continue;}
						if("NNANNNNANN".equals(s)){retval+=1350;continue;}
						if("NEANNNNANN".equals(s)){retval+=1150;continue;}
						if("NEAENNNANN".equals(s)){retval+=1200;continue;}
						if("NEAENENANN".equals(s)){retval+=1000;continue;}
						if("NEAEEENANN".equals(s)){retval+=550;continue;}
						if("NEAEENNANN".equals(s)){retval+=1000;continue;}
						if("NEANNENANN".equals(s)){retval+=950;continue;}
						if("NEANEENANN".equals(s)){retval+=500;continue;}
						if("NEANENNANN".equals(s)){retval+=950;continue;}
						if("NNAENNNANN".equals(s)){retval+=1400;continue;}
						if("NNAENENANN".equals(s)){retval+=1200;continue;}
						if("NNAEEENANN".equals(s)){retval+=950;continue;}
						if("NNAEENNANN".equals(s)){retval+=1200;continue;}
						if("NNANNENANN".equals(s)){retval+=1150;continue;}
						if("NNANEENANN".equals(s)){retval+=900;continue;}
						if("NNANENNANN".equals(s)){retval+=1150;continue;}
						if("NNAANNNANN".equals(s)){retval+=1300;continue;}
						if("NEAANNNANN".equals(s)){retval+=1100;continue;}
						if("NEAANENANN".equals(s)){retval+=900;continue;}
						if("NEAAEENANN".equals(s)){retval+=450;continue;}
						if("NEAAENNANN".equals(s)){retval+=900;continue;}
						if("NNAANENANN".equals(s)){retval+=1100;continue;}
						if("NNAAEENANN".equals(s)){retval+=850;continue;}
						if("NNAAENNANN".equals(s)){retval+=1100;continue;}
						if("NNAANANANN".equals(s)){retval+=1250;continue;}
						if("NEAANANANN".equals(s)){retval+=1050;continue;}
						if("NEAAEANANN".equals(s)){retval+=1100;continue;}
						if("NNAAEANANN".equals(s)){retval+=1300;continue;}
						if("NNAAAANANN".equals(s)){retval+=450;continue;}
						if("NEAAAANANN".equals(s)){retval+=250;continue;}
						if("NNAAANNANN".equals(s)){retval+=450;continue;}
						if("NEAAANNANN".equals(s)){retval+=250;continue;}
						if("NEAAAENANN".equals(s)){retval+=250;continue;}
						if("NNAAAENANN".equals(s)){retval+=450;continue;}
						if("NNANNANANN".equals(s)){retval+=1300;continue;}
						if("NEANNANANN".equals(s)){retval+=1100;continue;}
						if("NEAENANANN".equals(s)){retval+=1150;continue;}
						if("NEAEEANANN".equals(s)){retval+=1200;continue;}
						if("NEANEANANN".equals(s)){retval+=1150;continue;}
						if("NNAENANANN".equals(s)){retval+=1350;continue;}
						if("NNAEEANANN".equals(s)){retval+=1400;continue;}
						if("NNANEANANN".equals(s)){retval+=1350;continue;}
						if("NNANAANANN".equals(s)){retval+=1300;continue;}
						if("NEANAANANN".equals(s)){retval+=1100;continue;}
						if("NEAEAANANN".equals(s)){retval+=1150;continue;}
						if("NNAEAANANN".equals(s)){retval+=1350;continue;}
						if("NNANANNANN".equals(s)){retval+=1300;continue;}
						if("NEANANNANN".equals(s)){retval+=1100;continue;}
						if("NEAEANNANN".equals(s)){retval+=1150;continue;}
						if("NEAEAENANN".equals(s)){retval+=1200;continue;}
						if("NEANAENANN".equals(s)){retval+=1150;continue;}
						if("NNAEANNANN".equals(s)){retval+=1350;continue;}
						if("NNAEAENANN".equals(s)){retval+=1400;continue;}
						if("NNANAENANN".equals(s)){retval+=1350;continue;}
						if("NNNANNNANN".equals(s)){retval+=1350;continue;}
						if("NENANNNANN".equals(s)){retval+=1150;continue;}
						if("NEEANNNANN".equals(s)){retval+=1200;continue;}
						if("NEEANENANN".equals(s)){retval+=1000;continue;}
						if("NEEAEENANN".equals(s)){retval+=550;continue;}
						if("NEEAENNANN".equals(s)){retval+=1000;continue;}
						if("NENANENANN".equals(s)){retval+=950;continue;}
						if("NENAEENANN".equals(s)){retval+=500;continue;}
						if("NENAENNANN".equals(s)){retval+=950;continue;}
						if("NNEANNNANN".equals(s)){retval+=1400;continue;}
						if("NNEANENANN".equals(s)){retval+=1200;continue;}
						if("NNEAEENANN".equals(s)){retval+=950;continue;}
						if("NNEAENNANN".equals(s)){retval+=1200;continue;}
						if("NNNANENANN".equals(s)){retval+=1150;continue;}
						if("NNNAEENANN".equals(s)){retval+=900;continue;}
						if("NNNAENNANN".equals(s)){retval+=1150;continue;}
						if("NNNANANANN".equals(s)){retval+=1300;continue;}
						if("NENANANANN".equals(s)){retval+=1100;continue;}
						if("NEEANANANN".equals(s)){retval+=1150;continue;}
						if("NEEAEANANN".equals(s)){retval+=1200;continue;}
						if("NENAEANANN".equals(s)){retval+=1150;continue;}
						if("NNEANANANN".equals(s)){retval+=1350;continue;}
						if("NNEAEANANN".equals(s)){retval+=1400;continue;}
						if("NNNAEANANN".equals(s)){retval+=1350;continue;}
						if("NNNAAANANN".equals(s)){retval+=450;continue;}
						if("NENAAANANN".equals(s)){retval+=250;continue;}
						if("NEEAAANANN".equals(s)){retval+=700;continue;}
						if("NNEAAANANN".equals(s)){retval+=900;continue;}
						if("NNNAANNANN".equals(s)){retval+=450;continue;}
						if("NENAANNANN".equals(s)){retval+=250;continue;}
						if("NEEAANNANN".equals(s)){retval+=700;continue;}
						if("NEEAAENANN".equals(s)){retval+=700;continue;}
						if("NENAAENANN".equals(s)){retval+=250;continue;}
						if("NNEAANNANN".equals(s)){retval+=900;continue;}
						if("NNEAAENANN".equals(s)){retval+=900;continue;}
						if("NNNAAENANN".equals(s)){retval+=450;continue;}
						if("NNNNNANANN".equals(s)){retval+=1350;continue;}
						if("NENNNANANN".equals(s)){retval+=1150;continue;}
						if("NEENNANANN".equals(s)){retval+=900;continue;}
						if("NEEENANANN".equals(s)){retval+=450;continue;}
						if("NEEEEANANN".equals(s)){retval+=500;continue;}
						if("NEENEANANN".equals(s)){retval+=950;continue;}
						if("NENENANANN".equals(s)){retval+=900;continue;}
						if("NENEEANANN".equals(s)){retval+=950;continue;}
						if("NENNEANANN".equals(s)){retval+=1200;continue;}
						if("NNENNANANN".equals(s)){retval+=1100;continue;}
						if("NNEENANANN".equals(s)){retval+=850;continue;}
						if("NNEEEANANN".equals(s)){retval+=900;continue;}
						if("NNENEANANN".equals(s)){retval+=1150;continue;}
						if("NNNENANANN".equals(s)){retval+=1100;continue;}
						if("NNNEEANANN".equals(s)){retval+=1150;continue;}
						if("NNNNEANANN".equals(s)){retval+=1400;continue;}
						if("NNNNAANANN".equals(s)){retval+=1350;continue;}
						if("NENNAANANN".equals(s)){retval+=1150;continue;}
						if("NEENAANANN".equals(s)){retval+=900;continue;}
						if("NEEEAANANN".equals(s)){retval+=450;continue;}
						if("NENEAANANN".equals(s)){retval+=900;continue;}
						if("NNENAANANN".equals(s)){retval+=1100;continue;}
						if("NNEEAANANN".equals(s)){retval+=850;continue;}
						if("NNNEAANANN".equals(s)){retval+=1100;continue;}
						if("NNNNANNANN".equals(s)){retval+=1350;continue;}
						if("NENNANNANN".equals(s)){retval+=1150;continue;}
						if("NEENANNANN".equals(s)){retval+=900;continue;}
						if("NEEEANNANN".equals(s)){retval+=450;continue;}
						if("NEEEAENANN".equals(s)){retval+=500;continue;}
						if("NEENAENANN".equals(s)){retval+=950;continue;}
						if("NENEANNANN".equals(s)){retval+=900;continue;}
						if("NENEAENANN".equals(s)){retval+=950;continue;}
						if("NENNAENANN".equals(s)){retval+=1200;continue;}
						if("NNENANNANN".equals(s)){retval+=1100;continue;}
						if("NNEEANNANN".equals(s)){retval+=850;continue;}
						if("NNEEAENANN".equals(s)){retval+=900;continue;}
						if("NNENAENANN".equals(s)){retval+=1150;continue;}
						if("NNNEANNANN".equals(s)){retval+=1100;continue;}
						if("NNNEAENANN".equals(s)){retval+=1150;continue;}
						if("NNNNAENANN".equals(s)){retval+=1400;continue;}
					}

				}
				
			}
			
		}
		
//		pattern = Pattern.sToPv2("xrxrxrxrxdxdxlxdxlxlxuxlxux", e.kscolour);
//		pMatches =ps.allStringMatch(sstring, pattern);
//		
//		if(!pMatches.isEmpty()) {
//			int counter=0;
//			for(ArrayList<Tuple> tlist: pMatches) {
//				if(!tlist.isEmpty()) {
//					boolean diagSide= ps.dirSideToBool(counter);
//					UDLR side = ps.dirNumToDir(counter);
//					counter++;
//					
//					UDLR r = side.diag(diagSide);
//					Tuple S0 = tlist.get(0).side2(side,r);
//					Tuple S1 = S0.side(r);
//					Tuple S2 = S1.side(r);
//					Tuple D0 = S1.side(side);
//
//
//					if(e.isThere(S0)||e.isThere(S2)||e.isThere(D0)) continue;
//					
//					retval+=500;
//					if(e.isEnemy(S1)) retval-=500;
//					if(e.isThere(S1)) retval+=5000;
//				}
//				
//			}
//			
//		}

		
		return retval;

	}

	
	
}
